version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgres/data/
    env_file:
      - ./bot/.env

  bot:
    build: ./bot/
    ports:
      - 8080:8080
    env_file:
      - ./bot/.env
    depends_on:
      - db

volumes:
  db_data:
